# Generated by Django 4.0.6 on 2022-07-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('indicativo_telefono', models.CharField(blank=True, default='+57', max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('sitio_web', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'grydd_empresa',
            },
        ),
        migrations.CreateModel(
            name='PuntosDeAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('geolocalizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntos_de_acceso', to='empresas.empresa')),
            ],
            options={
                'db_table': 'grydd_puntos_de_acceso',
            },
        ),
    ]
